spring.application.name=account-service
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://fmeleesa_db_user:JiXVGIBGODZjh0BK@cluster0.76r4pl7.mongodb.net/ridelink_account_db?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=ridelink_account_db
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
